artifact_location: file:C:/Users/Natsu/OneDrive/เดสก์ท็อป/Work/Project-Solar/Solar-detect-yolo/runs/mlflow/467276811639495299
creation_time: 1773006556564
experiment_id: '467276811639495299'
last_update_time: 1773006556564
lifecycle_stage: active
name: solar_detection
