artifact_location: file:C:/Users/Natsu/OneDrive/เดสก์ท็อป/Work/Project-Solar/Solar-detect-yolo/runs/mlflow/0
creation_time: 1773006556548
experiment_id: '0'
last_update_time: 1773006556548
lifecycle_stage: active
name: Default
