artifact_uri: file:C:/Users/Natsu/OneDrive/เดสก์ท็อป/Work/Project-Solar/Solar-detect-yolo/runs/mlflow/467276811639495299/f000636dc52a498ea6b00d639677b7fa/artifacts
end_time: 1773009256134
entry_point_name: ''
experiment_id: '467276811639495299'
lifecycle_stage: active
run_id: f000636dc52a498ea6b00d639677b7fa
run_name: yolo_world_tuning
source_name: ''
source_type: 4
source_version: ''
start_time: 1773006557472
status: 3
tags: []
user_id: Natsu
